### PR TITLE
Commands & Operations take 2

### PR DESCRIPTION
**Pull request by kreczko**
SwatchCommands is mostly Commands with a few changes. It will be renamed before any merge.
Main contributions here are tests.

TODO:
 - [x] Commands are implemented in the packages (service, processor, system)
 - [x] How to add Commands/Operations to ActionHandlers? In the Processor/Service/System factories? The reason I am asking is ```void registerCommand(std::string aName, Command* aCmd);``` vs ```template<typename C>
    void registerCommand(std::string aName );```
 - [x] IN the above, where would the operation get the FSM from?
 - [x] replaced ```swatch::system::test::DummyProcessor``` with ```swatch::processor::test::DummyProcessor```

### CODE REVIEW

**Comment by kreczko** [comment]
## To discuss tomorrow
@alessandrothea 
additional information in core::Operation (like in core::Command)
 - ```progress()``` and ```progressMsg()```
 - ```status()``` and ```statusMsg()```
 - setError, setWarning, setDone, etc
 - probably extract the interface from the above into a separate class (<something>Information) and have both Command and Operation derive from it in order to minimise code duplication.
 - ```result()```?

**Comment by alessandrothea** [comment]
Let's add Carlos

-a

> On 10 Mar 2015, at 13:07, Luke Kreczko <notifications@github.com> wrote:
> 
> To discuss tomorrow
> 
> @alessandrothea
> additional information in core::Operation (like in core::Command)
> 
> 	• progress() and progressMsg()
> 	• status() and statusMsg()
> 	• setError, setWarning, setDone, etc
> 	• probably extract the interface from the above into a separate class (Information) and have both Command and Operation derive from it in order to minimise code duplication.
> 	• result()?
> —
> Reply to this email directly or view it on GitHub.
> 

__________________________________________________________________________

Alessandro Thea
Postdoctoral Research Associate
Particle Physics Department
Rutherford Appleton Laboratory,
Oxfordshire OX11 0QX,
United Kingdom

Office: 40-1-b20 (CERN)
Email: Alessandro.Thea@cern.ch
Phone: +41 76 487 1800 (mobile)

**Comment by kreczko** [comment]
What is his github username?

**Comment by alessandrothea** [comment]
OK

On 10 March 2015 at 13:15, Alessandro Thea <Alessandro.Thea@cern.ch> wrote:

> Let's add Carlos
>
> -a
>
> > On 10 Mar 2015, at 13:07, Luke Kreczko <notifications@github.com> wrote:
> >
> > To discuss tomorrow
> >
> > @alessandrothea
> > additional information in core::Operation (like in core::Command)
> >
> >       • progress() and progressMsg()
> >       • status() and statusMsg()
> >       • setError, setWarning, setDone, etc
> >       • probably extract the interface from the above into a separate
> class (Information) and have both Command and Operation derive from it in
> order to minimise code duplication.
> >       • result()?
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> __________________________________________________________________________
>
> Alessandro Thea
> Postdoctoral Research Associate
> Particle Physics Department
> Rutherford Appleton Laboratory,
> Oxfordshire OX11 0QX,
> United Kingdom
>
> Office: 40-1-b20 (CERN)
> Email: Alessandro.Thea@cern.ch
> Phone: +41 76 487 1800 (mobile)
>
>


-- 
Carlos Ghabrous Larrea
L1 Trigger - CMS Experiment
University of Wisconsin
Tel.    +41 22 767 16 26
Mob. + 41 76 487 91 80

**Comment by kreczko** [comment]
Example for an Operation: https://svnweb.cern.ch/trac/cactus/browser/trunk/cactusprojects/gt/ts/cell/src/common/Configuration.cc

**Pull request closed without merging**
